### ISSUE TITLE
'fixed by commit' classification checks sometimes raise an exception

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#131]
```
 90% 22118/24599 [50:10<9:48:54, 14.24s/it] 2020-04-01 14:15:01,352:INFO:scripts.test_scheduling_history_retriever:Analyzing 1466d7d6110279cf167ab8b1567be693df5d7c3c at the label level...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/scripts/test_scheduling_history_retriever.py", line 150, in generate_push_data
    list(push.get_possible_regressions(runnable)),
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 638, in get_possible_regressions
    for name, count in self.get_regressions(runnable_type).items()
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 580, in get_regressions
    if not self.backedout and not self.bustage_fixed_by:
  File "/usr/local/lib/python3.8/site-packages/adr/util/memoize.py", line 45, in __get__
    setattr(instance, name, self.func(instance))
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 552, in bustage_fixed_by
    for name in self.get_candidate_regressions("label")
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 510, in get_candidate_regressions
    is_classified_as_cause = self._is_classified_as_cause(
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 469, in _is_classified_as_cause
    if backout[:12] == self.backedoutby[:12]:
TypeError: 'NoneType' object is not subscriptable
```

One of backout or self.backedoutby was none, we should guard against that.

**Comment by marco-c** [comment]
The fix was super-easy, so I just went ahead and landed it.
