### ISSUE TITLE
Assertion error with some pushes "should have no results"

### ISSUE THREAD

**Issue by camd** [mozilla/mozci#348]
I'm hitting this assertion error:

    AssertionError: A3VK8DX0QqSNS7KiDqwJbA : test-windows10-64-shippable/opt-talos-chrome-e10s should have no results

It appears to be with `mozilla-central` push `41effaf024a55426f4486278364dea1117ed6571`

The trace I get is:

     | [2020-11-06 16:19:37,028] ERROR [django.request:228] Internal Server Error: /api/project/try/push/health_summary/
     | Traceback (most recent call last):
     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
     |     response = get_response(request)
     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
     |     response = self.process_exception_by_middleware(e, request)
     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
     |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
     |     return view_func(*args, **kwargs)
     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
     |     return self.dispatch(request, *args, **kwargs)
     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
     |     response = self.handle_exception(exc)
     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
     |     self.raise_uncaught_exception(exc)
     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
     |     raise exc
     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
     |     response = handler(request, *args, **kwargs)
     |   File "/app/treeherder/webapp/api/push.py", line 218, in health_summary
     |     likely_regression_labels = list(mozciPush.get_likely_regressions('label'))
     |   File "/mozci/mozci/push.py", line 974, in get_likely_regressions
     |     for name, count in self.get_regressions(runnable_type).items()
     |   File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 27, in method_call
     |     cache[(args, kwargs_tuple)] = self.func(instance, *args, **kwargs)
     |   File "/mozci/mozci/push.py", line 898, in get_regressions
     |     runnable_summaries = getattr(other, f"{runnable_type}_summaries")
     |   File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 46, in __get__
     |     setattr(instance, name, self.func(instance))
     |   File "/mozci/mozci/push.py", line 482, in label_summaries
     |     for task in self.tasks:
     |   File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 46, in __get__
     |     setattr(instance, name, self.func(instance))
     |   File "/mozci/mozci/push.py", line 292, in tasks
     |     tasks = [Task.create(**task) for task in tasks]
     |   File "/mozci/mozci/push.py", line 292, in <listcomp>
     |     tasks = [Task.create(**task) for task in tasks]
     |   File "/mozci/mozci/task.py", line 168, in create
     |     return TestTask(**kwargs)
     |   File "<string>", line 12, in __init__
     |   File "/mozci/mozci/task.py", line 251, in __post_init__
     |     ), f"{self.id} : {self.label} should have no results"
     | AssertionError: B5OiXzdqQauNnZT4oBN5Ow : test-macosx1014-64-shippable-qr/opt-talos-perf-reftest-singletons-fis-e10s should have no results

**Comment by camd** [comment]
When I throw a `print` statement in `task.py` in `TestTask.__post_init___` in the `if is_no_groups_suite(self.label):` check on line 243, I can see that it mostly gets `None` but then there's one case of ` [GroupResult(group='default', ok=True)]`

**Comment by camd** [comment]
ok, this was my error.  I will exclude Groups with the name of `default`.  That seems to fix it.
