### ISSUE TITLE
zstandard is not optional

### ISSUE THREAD

**Issue by La0** [mozilla/mozci#545]
The zstandard package is marked as an optional dependency, but if I try to install with:

```console
poetry install --no-dev 
```

A later execution of `mozci` will result in an immediate crash:

```console
2021-11-08 17:24:03.153 | WARNING  | mozci.configuration:__init__:130 - Configuration path /root/.config/mozci/config.toml is not a file.
Traceback (most recent call last):
  File "/usr/local/bin/mozci", line 2, in <module>
    from mozci.console.application import cli
  File "/src/mozci/__init__.py", line 2, in <module>
    from mozci.configuration import config  # noqa
  File "/src/mozci/configuration.py", line 187, in <module>
    config = Configuration()
  File "/src/mozci/configuration.py", line 135, in __init__
    self.cache = CustomCacheManager(self._config["cache"])
  File "/src/mozci/configuration.py", line 90, in __init__
    self.register_serializer("compressedpickle", CompressedPickleSerializer())
  File "/src/mozci/util/cache_stores.py", line 256, in __init__
    import zstandard
ModuleNotFoundError: No module named 'zstandard'
```

**Comment by marco-c** [comment]
Yeah, it was supposed to only be imported when using the CompressedPickleSerializer, but a CompressedPickleSerializer is instantiated no matter what the config is (https://github.com/mozilla/mozci/blob/d3c50aaa76fe8dc72b1b255fc73e9586029df7a3/mozci/configuration.py#L90).

I don't mind removing it from the optional list and adding it to the required one, @ahal do you?

**Comment by ahal** [comment]
Ah yeah, making it required is probably easiest then.

Alternatively we could try to avoid using it in the event we don't have a cache configured.
