### ISSUE TITLE
Don't fail when a 'fixed by commit' revision does not exist, simply act as if the classification wasn't there

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#56]
```
Traceback (most recent call last):
  File "/builds/worker/checkouts/ci-recipes/recipes/push_data.py", line 57, in run
    list(push.get_possible_regressions(args.runnable)),
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 519, in get_possible_regressions
    return set(name for name, count in self.get_regressions(runnable_type).items() if count > 0)
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/adr/util/memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 479, in get_regressions
    for name, child_count in self.get_candidate_regressions(runnable_type).items():
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/adr/util/memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 442, in get_candidate_regressions
    for note in fixed_by_commit_classification_notes
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 442, in <genexpr>
    for note in fixed_by_commit_classification_notes
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 46, in is_backout
    res = get_automation_relevance(branch, rev)
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/mozci/push.py", line 35, in get_automation_relevance
    r.raise_for_status()
  File "/root/.cache/pypoetry/virtualenvs/ci-recipes-oLflYCg_-py3.7/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hg.mozilla.org/integration/autoland/json-automationrelevance/4a946bbf08b
```

We should handle it gracefully instead of raising an exception.

**Comment by jmaher** [comment]
this is found in: https://hg.mozilla.org/integration/autoland/raw-rev/44a946bbf08b, I would say 2% of the fixed_by_commit notes will be invalid.
sometimes it is 12 vs 40 character hash, so I found that I needed to convert all revs to 12 chars to match up.

Do we post process this with manual work and data files?
do we edit the treeherder database with the right data?
do we ignore?

**Comment by marco-c** [comment]
Another error when analyzing 13a7265ed7316f2e97300128cb17b02151cf4d43:
```
    for other, candidate_regressions in self._iterate_failures(runnable_type):
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 504, in _iterate_failures
    is_classified_as_cause = self._is_classified_as_cause(
  File "/usr/local/lib/python3.8/site-packages/mozci/push.py", line 431, in _is_classified_as_cause
    if len(fix_hgmo.backouts) == 0:
  File "/usr/local/lib/python3.8/site-packages/mozci/util/hgmo.py", line 76, in backouts
    for changeset in self.changesets
  File "/usr/local/lib/python3.8/site-packages/mozci/util/hgmo.py", line 49, in changesets
    return self._get_resource(url)["changesets"]
  File "/usr/local/lib/python3.8/site-packages/mozci/util/hgmo.py", line 38, in _get_resource
    r = get_session("hgmo").get(url)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='hg.mozilla.org', port=443): Max retries exceeded with url: /integration/autoland/json-automationrelevance/%60549556b9fb8 (Caused by ResponseError('too many 500 error responses'))
```

I'd say we should just act as if these classifications didn't exist.

**Comment by ahal** [comment]
Note, if you strip the `%` out of that last example, it works:
https://hg.mozilla.org/integration/autoland/json-automationrelevance/549556b9fb8

Maybe we should strip all invalid characters from the start/end of sheriff classifications as well?

**Comment by jmaher** [comment]
I agree- can we get an idea of how many times or what percent this occurs?
I suspect it is <2%

**Comment by ahal** [comment]
Also worth noting that the fact `hgmo` returns 500 seems like a bug on that end, but it's preventing the `HGMO` class from raising a `PushNotFoundError`:
https://github.com/mozilla/mozci/blob/master/mozci/util/hgmo.py#L40

I wonder if we should also raise `PushNotFound` when other status codes are returned.

**Comment by marco-c** [comment]
> I agree- can we get an idea of how many times or what percent this occurs?

It is very very rare, I've seen it just a few times in over 20k pushes.

**Comment by marco-c** [comment]
I was tired of seeing the errors in the logs, so I've just decided to ignore them by raising a PushNotFound error in such cases: https://github.com/mozilla/mozci/pull/237.
