### ISSUE TITLE
Exception trying to create child pushes on pushes that don't have children

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#80]
Mozci looks at child pushes to try and deteremine whether a failure is a regression. But if the current push is tip (has no children) an exception gets raised:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ahal/dev/adr/adr/util/memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/ahal/dev/mozci/mozci/push.py", line 458, in get_regressions
    for name, (child_count, status) in self.get_candidate_regressions(runnable_type).items():
  File "/home/ahal/dev/adr/adr/util/memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/ahal/dev/mozci/mozci/push.py", line 436, in get_candidate_regressions
    other = other.child
  File "/home/ahal/dev/adr/adr/util/memoize.py", line 44, in __get__
    setattr(instance, name, self.func(instance))
  File "/home/ahal/dev/mozci/mozci/push.py", line 128, in child
    return self.create_push(self.id + 1)
  File "/home/ahal/dev/mozci/mozci/push.py", line 103, in create_push
    )[str(push_id)]
KeyError: '109552'
```

We should handle this case better.

**Comment by marco-c** [comment]
Definitely, I haven't cared much about this as I always analyze "historical" pushes.

**Comment by ahal** [comment]
Yeah, not a high priority, but wanted to get it on file.

**Comment by ahal** [comment]
So we could either raise a better exception like Kyle suggests in issue #93, or we could simply do the best we can (i.e not fail at all). I can see arguments in both directions.
